package com.keep.going;

import java.util.List;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import com.keep.going.repository.MemberRepository;
import com.keep.going.vo.Member;

@SpringBootTest
class RepositoryTest {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private MemberRepository userRepository;
	
	@Test
	void contextLoads() {
		List<Member> d = (List<Member>) userRepository.findAll();
		System.out.println(d.size());
		System.out.println(d);
		System.out.println(d.get(0).getId());
		System.out.println(d.get(0).getName());
		System.out.println(d.get(0).getPassword());
	}

}
