package com.keep.going.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import com.keep.going.repository.MemberRepository;
import com.keep.going.vo.Member;

@Controller
public class MemberController {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private MemberRepository userRepository;


	@GetMapping(path = "/all")
	public @ResponseBody Iterable<Member> getAllUsers() {
// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
}
